### ISSUE TITLE
Reversing engineering the protocol

### ISSUE THREAD

**Issue by kennedyoliveira** [ymgve/desse#1]
Hello!

I'm really interested in how you reverse engineered the protocol to craft the server? Do you mind sharing the details?

Can we get more data to implement the missing features?

Thanks for this awesome piece of work :)

**Comment by ymgve** [comment]
What missing features are you talking about that you feel are missing?

Some overall information about the reverse engineering process is in this interview: https://www.eurogamer.net/articles/2018-04-10-how-one-enterprising-fan-brought-demons-souls-back-to-life

**Comment by dixonte** [comment]
One thing I would like is the ability to set world tendency, like world tendency events they used to have towards the end of the game's life. This would help keep the game fully playable without an active player base.

**Comment by kennedyoliveira** [comment]
Thanks for the link @ymgve, regarding the feature actually I don't feel anything is missing to be honest, I just said that because of the readme note:

> This is a very quick and dirty server emulator that supports the most basic features

It sounded to me that there is more to be done. Unfortunately I sold my PS3 recently before knowing about your work otherwise I'll would join and play a bit
