### ISSUE TITLE
A question about Uncharted 2's multiplayer!

### ISSUE THREAD

**Issue by Krihi44** [ymgve/desse#3]
Dear ymgve!

First of all, I'd like to say a big thank you for your enthusiasm and hard work to bring back the Demon's Souls' online functions back to life.
You made countless of fan's entertainment more happier and we/they will always be grateful for your service.

I write you about another game's multiplayer. This game, this multiplayer means a lot to us. We can thank so many friends, so much memories, fantastic, euphoric and triumphant moments that there are not enough words to describe them all. This multiplayer is a part of our gamer life and maybe I can say that this game is so important to us that the Demon's Souls' multiplayer is to you and the Demon's Souls Community. 
And this game is Uncharted 2.

Maybe you heard that Sony/Naughty Dog shutted down the game's servers on September 3rd. Since then, our gamer life changed. We couldn't connect to this masterpiece's online multiplayer, we don't see that even one of us would play with this game now. Our Friend List vacancies and it's a so weird feeling. :/ 

As we saw that you and the other folks revived the Demon's Souls'online multiplayer and created a private server for this game, we began to think that can this method maybe work with Uncharted 2 as well?
I was online when Sony/Naughty Dog shutted down the servers. We could play even after the shutdown, like as before: we could play both competitive and cooperative modes, launch custom games, watch the cinema files, search for players and so one. But! If we leaved the multiplayer, we couldn't reconnect again. 

Sadly I don't know so much about this, but I guess that the servers didn't have such an important role in this game's multiplayer. (If it'd had, then we should have kicked from the game at the time of the shutdown.) 
So I'd like to ask you: as a professional,  what do you think? Can be this game's phenomenal multiplayer revived like Demon's Souls?

I captured the game's network traffic multiple times. (I captured 4-5 different times.) 
What do you think? Could these captures be enough for a possible revival? Or do we need another datas?

If you don't want to help me/us with this project, no problem. I just want to ask that can you recommend someone who has skills and knowledge about this like you? Or can you show me some studies where I can learn it and make it on my own?

This multiplayer is just too perfect to let it be dead on the digital graveyard. 
We could be very happy and grateful if you can show some us some hope that we can see our good old friend again. :) 

I'm sorry if it was too long, but thank you very much for reading it and wish you a nice day! :) 

Sincerely,

Krihi44
An Uncharted 2 multiplayer fan :)

**Comment by ymgve** [comment]
Sorry, I don't have any interest in Uncharted 2 Multiplayer, so I won't assist.
